#!/usr/bin/env python3
"""
Demo script to generate a book for 5 real pets from Alexandria, VA
using the asset assembler workflow functions.
"""

import json
import os
import sys
from pathlib import Path

# Add the current directory to path to import main functions
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from main import create_pdf_book, create_ppt

def load_alexandria_pets():
    """Load the 5 pets from Alexandria, VA JSON file"""
    json_path = Path(__file__).parent.parent / "pets_alexandria_va.json"
    
    with open(json_path, 'r') as f:
        pets_data = json.load(f)
    
    # Extract the first 5 pets and format them for our workflow
    pets = []
    for pet_data in pets_data[:5]:
        # Extract photo URLs
        photos = []
        for photo in pet_data.get("photos", []):
            if "large" in photo:
                photos.append(photo["large"])
        
        # Create simplified pet format
        pet = {
            "name": pet_data["name"],
            "description": f"{pet_data['breeds']['primary']} {pet_data['type'].lower()}, {pet_data['age'].lower()}, {pet_data['gender'].lower()}. {pet_data.get('description', 'A wonderful pet looking for a home.')}",
            "photos": photos,
            "type": pet_data["type"],
            "breed": pet_data["breeds"]["primary"],
            "age": pet_data["age"],
            "gender": pet_data["gender"],
            "tags": pet_data.get("tags", []),
            "organization": pet_data["organization_id"],
            "contact": pet_data.get("contact", {}).get("email", ""),
            "url": pet_data.get("url", "")
        }
        pets.append(pet)
    
    return pets

def create_mock_content(pets):
    """Create mock content structure as if generated by content_generator"""
    content = {
        "stories": [],
        "images": [],
        "badges": [],
        "videos": []
    }
    
    # Create humorous adventure stories for each pet
    story_templates = {
        "Pepper": "Pepper, the mysterious black cat, once spent an entire afternoon plotting the perfect heist to steal the neighbor's tuna sandwich. With ninja-like stealth and independent spirit, she successfully executed 'Operation Sandwich Snatch' but was caught red-pawed when she fell asleep in the evidence (the empty plate). Now she's looking for a family who appreciates her criminal mastermind potential and her adorable snoring habits.",
        
        "Winnie": "Winnie, the dignified Russian Blue senior, runs the most exclusive retirement community in the shelter. She hosts daily tea parties (water bowl gatherings) where she shares wisdom about the finer things in life: sunny windowsills, premium catnip, and the art of the perfect nap. Her motto: 'Age is just a number, but nap time is sacred.' She's seeking a retirement home where she can continue her reign as the neighborhood's most distinguished feline philosopher.",
        
        "Zebra": "Zebra, the tuxedo cat with a name that confuses everyone, decided to embrace his identity crisis by becoming the shelter's official greeter. He jumps into every visitor's arms, convinced he's actually a dog trapped in a cat's body. His daily routine includes fetch practice, tail-wagging attempts, and hosting 'How to Be More Dog' workshops for confused cats. He's looking for a family who won't mind his existential crisis and will love his enthusiastic personality.",
        
        "Rebekah": "Rebekah, the German Shepherd mix, appointed herself as the shelter's Chief Security Officer and Head of Fun Activities. She takes her job seriously, patrolling the grounds for suspicious squirrels and organizing daily exercise programs for the other dogs. Her resume includes: Professional Tail Wagger, Expert Treat Tester, and Certified Good Girl. She's seeking a family who needs a loyal companion and doesn't mind her over-enthusiasm for protecting the mailman from dangerous letters.",
        
        "Crouton": "Crouton, the golden mixed breed, got his name after an unfortunate incident involving a salad bar and his insatiable curiosity. He's since become the shelter's food critic, rating every meal and treat with sophisticated palate. His reviews are legendary: 'The kibble has hints of chicken with a robust crunch - 4 paws out of 5.' He's looking for a family who appreciates fine dining and doesn't mind sharing their snacks with a four-legged food connoisseur."
    }
    
    for pet in pets:
        name = pet["name"]
        
        # Create story
        story = story_templates.get(name, f"{name} is an amazing {pet['type'].lower()} with a wonderful personality, looking for a loving home where they can share their unique charm and bring joy to a family.")
        content["stories"].append({"pet": name, "story": story})
        
        # Use real photos if available, otherwise create mock URLs
        if pet["photos"]:
            image_url = pet["photos"][0]  # Use first photo
        else:
            image_url = f"https://example.com/{name.lower()}_photo.jpg"
        content["images"].append({"pet": name, "image_url": image_url})
        
        # Mock badge and video URLs
        content["badges"].append({"pet": name, "badge_url": f"https://example.com/{name.lower()}_badge.jpg"})
        content["videos"].append({"pet": name, "video_url": f"https://example.com/{name.lower()}_video.mp4"})
    
    return content

def print_pet_info(pets):
    """Print information about the pets"""
    print("🐾 Alexandria, VA Pets Featured in This Book:")
    print("=" * 60)
    
    for i, pet in enumerate(pets, 1):
        print(f"\n{i}. {pet['name']} - {pet['breed']} {pet['type']}")
        print(f"   Age: {pet['age']} | Gender: {pet['gender']}")
        print(f"   Tags: {', '.join(pet['tags'])}")
        print(f"   Photos: {len(pet['photos'])} available")
        print(f"   Organization: {pet['organization']}")
        print(f"   Contact: {pet['contact']}")
        if pet['url']:
            print(f"   Petfinder: {pet['url']}")
        print(f"   Description: {pet['description'][:100]}...")

def main():
    """Main function to generate the book"""
    print("📚 Generating Pet Adoption Book for Alexandria, VA Pets")
    print("=" * 60)
    
    try:
        # Load real pet data
        pets = load_alexandria_pets()
        print(f"✅ Loaded {len(pets)} pets from Alexandria, VA")
        
        # Print pet information
        print_pet_info(pets)
        
        # Create mock content (simulating content_generator output)
        print("\n🎨 Creating content for pets...")
        content = create_mock_content(pets)
        
        # Generate PDF book
        print("\n📖 Generating PDF book...")
        pdf_path = create_pdf_book(content)
        pdf_size = os.path.getsize(pdf_path)
        print(f"✅ PDF book created: {pdf_path} ({pdf_size:,} bytes)")
        
        # Generate PPT presentation
        print("\n🎭 Generating PowerPoint presentation...")
        ppt_path = create_ppt(content)
        ppt_size = os.path.getsize(ppt_path)
        print(f"✅ PPT presentation created: {ppt_path} ({ppt_size:,} bytes)")
        
        # Summary
        print("\n" + "=" * 60)
        print("📋 GENERATION COMPLETE!")
        print("=" * 60)
        print(f"📖 PDF Book: {pdf_path}")
        print(f"🎭 PowerPoint: {ppt_path}")
        print(f"🐾 Featured Pets: {len(pets)}")
        print(f"📍 Location: Alexandria, VA")
        print(f"🏠 Organizations: {', '.join(set(pet['organization'] for pet in pets))}")
        
        print("\n💡 Next Steps:")
        print("1. Open the PDF to see the multi-chapter pet adoption book")
        print("2. View the PowerPoint presentation with pet stories and photos")
        print("3. Contact the shelters to adopt these wonderful pets!")
        print("4. The files use temporary paths - copy them if you want to keep them")
        
        return {
            "pdf_path": pdf_path,
            "ppt_path": ppt_path,
            "pets_count": len(pets),
            "pets": pets
        }
        
    except Exception as e:
        print(f"\n❌ Error generating book: {e}")
        import traceback
        traceback.print_exc()
        return None

if __name__ == "__main__":
    result = main()
    if result:
        print(f"\n🎉 Success! Generated book with {result['pets_count']} Alexandria pets!")
    else:
        print("\n💥 Failed to generate book.")
        sys.exit(1) 