import asyncio
from typing import Annotated, Any, Dict

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from pptx import Presentation
from PIL import Image
import requests
from io import BytesIO
from genai_session.session import GenAISession
from genai_session.utils.context import GenAIContext

import os
import tempfile
import qrcode
from pptx.util import Inches

AGENT_JWT = "PLACEHOLDER_JWT"  # Replace with actual JWT after registration
session = GenAISession(jwt_token=AGENT_JWT)


def create_pdf_book(content):
    stories = content["stories"]
    images = {img['pet']: img['image_url'] for img in content["images"]}
    story_images = {img['pet']: img['image_url'] for img in content.get("story_images", [])}
    badges = {b['pet']: b['badge_url'] for b in content["badges"]}
    videos = {v['pet']: v['video_url'] for v in content["videos"]}
    is_multi = len(stories) > 1
    with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as tmp_pdf:
        c = canvas.Canvas(tmp_pdf.name, pagesize=letter)
        # Cover page
        c.setFont("Helvetica-Bold", 24)
        c.drawString(100, 750, "Pet Adoption Stories")
        c.setFont("Helvetica", 12)
        c.drawString(100, 720, "Featuring Real Pets from Alexandria, VA")
        if not is_multi and stories:
            pet = stories[0]['pet']
            img_url = images.get(pet)
            if img_url:
                response = requests.get(img_url)
                img = Image.open(BytesIO(response.content))
                img_path = tempfile.mktemp(suffix='.jpg')
                img.save(img_path)
                c.drawImage(img_path, 100, 400, width=400, height=300)
                os.remove(img_path)
        else:
            # For multi, add first pet's photo as cover
            if stories:
                pet = stories[0]['pet']
                img_url = images.get(pet)
                if img_url:
                    response = requests.get(img_url)
                    img = Image.open(BytesIO(response.content))
                    img_path = tempfile.mktemp(suffix='.jpg')
                    img.save(img_path)
                    c.drawImage(img_path, 100, 400, width=400, height=300)
                    os.remove(img_path)
        c.showPage()
        # Chapters
        for story in stories:
            pet = story['pet']
            c.setFont("Helvetica-Bold", 18)
            title = f"{pet}'s Adventure" if not is_multi else f"Chapter: {pet}'s Adventure"
            c.drawString(100, 750, title)
            y = 700
            c.setFont("Helvetica", 12)
            story_text = story['story'].replace('\n', ' ')
            # Simple text wrapping (for demo)
            words = story_text.split()
            line = ''
            for word in words:
                if len(line) + len(word) > 80:
                    c.drawString(100, y, line)
                    y -= 15
                    line = word + ' '
                else:
                    line += word + ' '
            if line:
                c.drawString(100, y, line)
                y -= 30
            # Real pet photo
            img_url = images.get(pet)
            if img_url:
                try:
                    response = requests.get(img_url)
                    if response.status_code == 200:
                        img = Image.open(BytesIO(response.content))
                        img_path = tempfile.mktemp(suffix='.jpg')
                        img.save(img_path)
                        c.drawString(100, y - 20, "Real Photo:")
                        c.drawImage(img_path, 100, y - 170, width=200, height=150)
                        os.remove(img_path)
                        y -= 190
                except Exception as e:
                    c.drawString(100, y - 20, f"Real Photo: (Unable to load)")
                    y -= 40
            # Story-specific image
            story_img_url = story_images.get(pet)
            if story_img_url and not story_img_url.startswith("https://generated-story-image.example.com"):
                try:
                    response = requests.get(story_img_url)
                    if response.status_code == 200:
                        img = Image.open(BytesIO(response.content))
                        img_path = tempfile.mktemp(suffix='.jpg')
                        img.save(img_path)
                        c.drawString(100, y - 20, "Story Illustration:")
                        c.drawImage(img_path, 320, y - 170, width=200, height=150)
                        os.remove(img_path)
                        y -= 190
                except Exception as e:
                    c.drawString(100, y - 20, f"Story Illustration: (Would be generated by GPT-Image-1)")
                    y -= 40
            elif story_img_url:
                c.drawString(100, y - 20, f"Story Illustration: (Would be generated by GPT-Image-1)")
                y -= 40
            # Badge
            badge_url = badges.get(pet)
            if badge_url and not badge_url.startswith("https://generated-badge.example.com"):
                try:
                    response = requests.get(badge_url)
                    if response.status_code == 200:
                        img = Image.open(BytesIO(response.content))
                        img_path = tempfile.mktemp(suffix='.jpg')
                        img.save(img_path)
                        c.drawImage(img_path, 100, y - 100, width=100, height=100)
                        os.remove(img_path)
                        y -= 120
                except Exception as e:
                    c.drawString(100, y - 20, f"Badge: (Would be generated)")
                    y -= 40
            elif badge_url:
                c.drawString(100, y - 20, f"Badge: (Would be generated)")
                y -= 40
            # Video QR
            video_url = videos.get(pet)
            if video_url:
                qr = qrcode.QRCode()
                qr.add_data(video_url)
                qr.make(fit=True)
                qr_img = qr.make_image(fill_color="black", back_color="white")
                qr_path = tempfile.mktemp(suffix='.png')
                qr_img.save(qr_path)
                c.drawString(100, y - 20, "Scan to watch video:")
                c.drawImage(qr_path, 100, y - 120, width=100, height=100)
                os.remove(qr_path)
                y -= 140
            c.showPage()
        c.save()
    return tmp_pdf.name

def create_ppt(content):
    stories = content["stories"]
    images = {img['pet']: img['image_url'] for img in content["images"]}
    story_images = {img['pet']: img['image_url'] for img in content.get("story_images", [])}
    badges = {b['pet']: b['badge_url'] for b in content["badges"]}
    videos = {v['pet']: v['video_url'] for v in content["videos"]}
    prs = Presentation()
    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    title = slide.shapes.title
    title.text = "Pet Adoption Stories"
    subtitle = slide.placeholders[1]
    subtitle.text = "Real Pets from Alexandria, VA Looking for Forever Homes"
    for story in stories:
        pet = story['pet']
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        title = slide.shapes.title
        title.text = f"{pet}'s Story"
        content_placeholder = slide.placeholders[1]
        content_placeholder.text = story['story']
        # Real pet photo
        img_url = images.get(pet)
        if img_url:
            try:
                response = requests.get(img_url)
                if response.status_code == 200:
                    img_path = tempfile.mktemp(suffix='.jpg')
                    with open(img_path, 'wb') as f:
                        f.write(response.content)
                    slide.shapes.add_picture(img_path, Inches(1), Inches(2), width=Inches(2.5))
                    os.remove(img_path)
            except Exception as e:
                # Add text placeholder if image fails
                textbox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(2.5), Inches(1))
                text_frame = textbox.text_frame
                p = text_frame.add_paragraph()
                p.text = "Real Photo\n(Unable to load)"
        # Story-specific image
        story_img_url = story_images.get(pet)
        if story_img_url and not story_img_url.startswith("https://generated-story-image.example.com"):
            try:
                response = requests.get(story_img_url)
                if response.status_code == 200:
                    story_img_path = tempfile.mktemp(suffix='.jpg')
                    with open(story_img_path, 'wb') as f:
                        f.write(response.content)
                    slide.shapes.add_picture(story_img_path, Inches(4), Inches(2), width=Inches(2.5))
                    os.remove(story_img_path)
            except Exception as e:
                # Add text placeholder if image fails
                textbox = slide.shapes.add_textbox(Inches(4), Inches(2), Inches(2.5), Inches(1))
                text_frame = textbox.text_frame
                p = text_frame.add_paragraph()
                p.text = "Story Illustration\n(GPT-Image-1)"
        elif story_img_url:
            # Add text placeholder for mock URL
            textbox = slide.shapes.add_textbox(Inches(4), Inches(2), Inches(2.5), Inches(1))
            text_frame = textbox.text_frame
            p = text_frame.add_paragraph()
            p.text = "Story Illustration\n(GPT-Image-1)"
        # Badge
        badge_url = badges.get(pet)
        if badge_url and not badge_url.startswith("https://generated-badge.example.com"):
            try:
                response = requests.get(badge_url)
                if response.status_code == 200:
                    badge_path = tempfile.mktemp(suffix='.jpg')
                    with open(badge_path, 'wb') as f:
                        f.write(response.content)
                    slide.shapes.add_picture(badge_path, Inches(7), Inches(2), width=Inches(1.5))
                    os.remove(badge_path)
            except Exception as e:
                # Add text placeholder if image fails
                textbox = slide.shapes.add_textbox(Inches(7), Inches(2), Inches(1.5), Inches(1))
                text_frame = textbox.text_frame
                p = text_frame.add_paragraph()
                p.text = "Badge\n(Generated)"
        elif badge_url:
            # Add text placeholder for mock URL
            textbox = slide.shapes.add_textbox(Inches(7), Inches(2), Inches(1.5), Inches(1))
            text_frame = textbox.text_frame
            p = text_frame.add_paragraph()
            p.text = "Badge\n(Generated)"
        # Video link - add as text box with hyperlink
        video_url = videos.get(pet)
        if video_url:
            # Add text box for video link
            textbox = slide.shapes.add_textbox(Inches(1), Inches(5.5), Inches(8), Inches(1))
            text_frame = textbox.text_frame
            p = text_frame.add_paragraph()
            r = p.add_run()
            r.text = f"Watch {pet}'s video: {video_url}"
            hlink = r.hyperlink
            hlink.address = video_url
    with tempfile.NamedTemporaryFile(suffix='.pptx', delete=False) as tmp_ppt:
        prs.save(tmp_ppt.name)
    return tmp_ppt.name


@session.bind(
    name="asset_assembler",
    description="Assembles stories and assets into books, PDFs, PPTs."
)
async def asset_assembler(
    agent_context: GenAIContext,
    content: Annotated[Dict[str, Any], "Generated content with stories and video/image URLs"],
    specification: Annotated[str, "Specification for assembly"] = ""
) -> Dict[str, str]:
    agent_context.logger.info(f"Assembling assets with specification: {specification}")
    pdf_path = create_pdf_book(content)
    ppt_path = create_ppt(content)
    return {"book_file": pdf_path, "ppt_file": ppt_path}


async def main():
    print("Asset Assembler agent started")
    await session.process_events()

if __name__ == "__main__":
    asyncio.run(main()) 